services:
  postgres:
    image: postgres:16
    container_name: account-transfer-postgres
    environment:
      POSTGRES_DB: account_transfer
      POSTGRES_USER: app_account_transfer
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: