spring.application.name=teste-backend

# Import .env
spring.config.import=optional:file:.env[.properties]

# Postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/account_transfer
spring.datasource.username=app_account_transfer
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true